testdjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from cars.views import liste_voitures, voitures_par_couleur

from django.urls import path
from cars.views import liste_voitures, voitures_par_couleur

urlpatterns = [
    path('', liste_voitures, name='home'),
    path('voitures/', liste_voitures, name='liste_voitures'),
    path('voitures-par-couleur/', voitures_par_couleur, name='voitures_par_couleur'),
]

cars/models.py
from django.db import models

class Couleur(models.Model):
    nom = models.CharField(max_length=50)

    def __str__(self):
        return self.nom

class Voiture(models.Model):
    marque = models.CharField(max_length=50)
    annee_creation = models.IntegerField()
    couleur = models.ForeignKey(Couleur, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.marque} ({self.annee_creation})"

cars/views.py
from django.shortcuts import render
from .models import Voiture, Couleur

def liste_voitures(request):
    voitures = Voiture.objects.all()
    return render(request, 'testdjango/cars/liste_voitures.html', {'voitures': voitures})

def voitures_par_couleur(request):
    couleurs = Couleur.objects.all()
    return render(request, 'testdjango/cars/voitures_par_couleur.html', {'couleurs': couleurs})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/testdjango/cars/liste_voitures.html
{% extends 'base.html' %}

{% block content %}
{% for voiture in voitures %}
    <p>{{ voiture.marque }} ({{ voiture.annee_creation }}) - {{ voiture.couleur.nom }}</p>
{% endfor %}
<h1>efzezaezezfa/h1>
{% endblock content %}

templates/testdjango/cars/voitures_par_couleur.html
{% extends 'base.html' %}

{% block content %}
{% for couleur in couleurs %}
    <h2>{{ couleur.nom }}</h2>
    {% for voiture in couleur.voiture_set.all %}
        <p>{{ voiture.marque }} ({{ voiture.annee_creation }})</p>
    {% endfor %}
{% endfor %}
<h1>efzezaezezfa/h1>
{% endblock content %}